### ISSUE TITLE
Enemies are not highlighted when ItemBlacklist is also installed

### ISSUE THREAD

**Issue by BrandonRosa** [SChinchi/TricornEliteEquipment#1]
Doesnt work when highlighting enemies with zetAspects enabled

**Comment by SChinchi** [comment]
Could you please provide more information as at the moment I can't replicate this.

Are elite enemies targetted properly with the tricorn custom target icon but activating the equipment does nothing? I would need the logs to see if an error occurs at that point.

Are enemies not highlighted at all? It might be a hook incompatibility - again logs would be helpful. If you have changed any config values from their defaults, that may be relevant as well. At the moment the only case I can think of this occuring is if you're targetting an umbra that has aspects as items.

This mod's behaviour is very simple; it checks if the target holds an equipment with a non-zero drop chance to both decide whether to highlight the target and what to drop when killing it with the tricorn. If either of these conditions is not satisfied, the tricorn won't do anything.

**Comment by BrandonRosa** [comment]
I'll send longs as soon as I can. As for the targeting, they 100% are targetable but when pressing the activation button nothing happens. I've tried this with vanilla and modded elites.

I'm not sure if this matters but when the aspects drop I've set them to drop as standard yellow items and not equipment. Thanks!

**Comment by SChinchi** [comment]
Make sure you provide a log with minimal mods required to reproduce the issue, along with any specific config settings/game scenarios. It will save time on any back and forth to reproduce the issue if the logs themselves don't reveal anything.

I know, for example, that just this mod and ZetAspects with default settings seems to behave as expected, at least early in the run.

**Comment by BrandonRosa** [comment]
Weirdly enough, any of the Elite effecting mods work fine with your mod. When I re-enable the rest of my mods though it stops working, so its gonna be hard to tell what mod is effecting it. I'll give annother shot at trying to figure out what mod is messing with it. 
![image](https://github.com/SChinchi/TricornEliteEquipment/assets/39537164/93491943-354a-4ca0-95dd-111776bd94de)
^Thats a screenshot of the console when I try to use equipment. 

This is the part of the log where its throwing errors when I attempt to use the equipment.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoR2.EquipmentSlot.FireBossHunter () (at <1d532be543be416b9db3594e4b62447d>:IL_009F)
DMD<PerformEquipmentAction>?228528384._RoR2_EquipmentSlot::PerformEquipmentAction (RoR2.EquipmentSlot this, RoR2.EquipmentDef equipmentDef) (at <94a3df558aa14310a2d170a74b1042fa>:IL_03EC)
DMD<>?228528384.Trampoline<RoR2.EquipmentSlot::PerformEquipmentAction>?1175468032 (RoR2.EquipmentSlot , RoR2.EquipmentDef ) (at <0e1a024c65c74d39a4646c88b0c12722>:IL_0020)
Bomber.Hook.EquipmentSlot_PerformEquipmentAction (On.RoR2.EquipmentSlot+orig_PerformEquipmentAction orig, RoR2.EquipmentSlot self, RoR2.EquipmentDef equipmentDef) (at <e820687bbe8646b1adde065593c26eaf>:IL_0163)
DMD<>?228528384.Hook<RoR2.EquipmentSlot::PerformEquipmentAction>?1674898304 (RoR2.EquipmentSlot , RoR2.EquipmentDef ) (at <d0921999d873485a91b58eb2478bb700>:IL_000A)
DMD<>?228528384.Trampoline<RoR2.EquipmentSlot::PerformEquipmentAction>?-2126489600 (RoR2.EquipmentSlot , RoR2.EquipmentDef ) (at <3a477764c8e74fdb99ea1a59d8e8f70c>:IL_0020)
Gunslinger.Gauntlet.EquipmentSlot_PerformEquipmentAction (On.RoR2.EquipmentSlot+orig_PerformEquipmentAction orig, RoR2.EquipmentSlot self, RoR2.EquipmentDef equipmentDef) (at <3dbadd0a47354302995b3037e9773d82>:IL_001B)
DMD<>?228528384.Hook<RoR2.EquipmentSlot::PerformEquipmentAction>?619971712 (RoR2.EquipmentSlot , RoR2.EquipmentDef ) (at <c2ce91961a3141e5b2d583e45a1a847f>:IL_000A)
DMD<>?228528384.Trampoline<RoR2.EquipmentSlot::PerformEquipmentAction>?430279680 (RoR2.EquipmentSlot , RoR2.EquipmentDef ) (at <700cd3d80f964c0e927157e04f6ed47f>:IL_0020)
BlightedElites.BlightedElitesPlugin.EquipmentSlot_PerformEquipmentAction (On.RoR2.EquipmentSlot+orig_PerformEquipmentAction orig, RoR2.EquipmentSlot self, RoR2.EquipmentDef equipmentDef) (at <18863fc0ac144fb695fa511f715ddc27>:IL_0001)
DMD<>?228528384.Hook<RoR2.EquipmentSlot::PerformEquipmentAction>?-1677411072 (RoR2.EquipmentSlot , RoR2.EquipmentDef ) (at <6825a2bce4b14ed1bf7dc70df31d581c>:IL_0014)
DMD<>?228528384.Trampoline<RoR2.EquipmentSlot::PerformEquipmentAction>?-436074496 (RoR2.EquipmentSlot , RoR2.EquipmentDef ) (at <5fdd0838d6764d508c627a4109cf28f2>:IL_0020)
MysticsRisky2Utils.BaseAssetTypes.BaseEquipment+<>c.<Init>b__11_0 (On.RoR2.EquipmentSlot+orig_PerformEquipmentAction orig, RoR2.EquipmentSlot self, RoR2.EquipmentDef equipmentDef2) (at <da933863d54a499f95fce40e8a2172f4>:IL_0049)
DMD<>?228528384.Hook<RoR2.EquipmentSlot::PerformEquipmentAction>?-799949568 (RoR2.EquipmentSlot , RoR2.EquipmentDef ) (at <5dc78578772e4ac9be5409a207b98441>:IL_0014)
DMD<>?228528384.Trampoline<RoR2.EquipmentSlot::PerformEquipmentAction>?-1184775168 (RoR2.EquipmentSlot , RoR2.EquipmentDef ) (at <839d1658946940b78764637c4757f991>:IL_0020)
MELTPlugin.MELTPlugin.MiniVoidRift_PerformEquipmentAction (On.RoR2.EquipmentSlot+orig_PerformEquipmentAction orig, RoR2.EquipmentSlot self, RoR2.EquipmentDef equipmentDef) (at <e40ef5a4702f43f0bcf1945bd44f91f7>:IL_0295)
DMD<>?228528384.Hook<RoR2.EquipmentSlot::PerformEquipmentAction>?-1967110272 (RoR2.EquipmentSlot , RoR2.EquipmentDef ) (at <d9eb6f01775245a7b6b027e9b8fbfe92>:IL_0014)
DMD<>?228528384.Trampoline<RoR2.EquipmentSlot::PerformEquipmentAction>?643036160 (RoR2.EquipmentSlot , RoR2.EquipmentDef ) (at <671540b03f6f4aa4a3cf639dd85ac0b6>:IL_0020)
Moonstorm.EquipmentModuleBase.PerformAction (On.RoR2.EquipmentSlot+orig_PerformEquipmentAction orig, RoR2.EquipmentSlot self, RoR2.EquipmentDef equipmentDef) (at <0c2e01bd7cf74bc199f52f73d921b323>:IL_003B)
DMD<>?228528384.Hook<RoR2.EquipmentSlot::PerformEquipmentAction>?1322445696 (RoR2.EquipmentSlot , RoR2.EquipmentDef ) (at <8039d3770bb34175995c6f6c4685af08>:IL_000A)
RoR2.EquipmentSlot.Execute () (at <1d532be543be416b9db3594e4b62447d>:IL_0031)
DMD<ExecuteIfReady>?228528384._RoR2_EquipmentSlot::ExecuteIfReady (RoR2.EquipmentSlot this) (at <6083e74569f9460bbd61a6bf6ea330ec>:IL_0028)
DMD<>?228528384.Trampoline<RoR2.EquipmentSlot::ExecuteIfReady>?986444800 (RoR2.EquipmentSlot ) (at <8fbc08172a2941749b57474f25e5d48d>:IL_0020)
BetterGameplay.BetterGameplayPlugin.EquipmentSlot_ExecuteIfReady (System.Func`2[T,TResult] orig, RoR2.EquipmentSlot self) (at <93f440288c324953b490e23e7a0dafe1>:IL_0043)
DMD<>?228528384.Hook<RoR2.EquipmentSlot::ExecuteIfReady>?2083285760 (RoR2.EquipmentSlot ) (at <07c58af71a514c33ac093711b84ceb2e>:IL_000A)
RoR2.EquipmentSlot.FixedUpdate () (at <1d532be543be416b9db3594e4b62447d>:IL_0277)

[LogOutput.log](https://github.com/SChinchi/TricornEliteEquipment/files/13641772/LogOutput.log)
^Ive attatched my log. Sorry that the info Ive given isnt too helpful right now, im gonna try to narrow the mod list in a bit.

**Comment by SChinchi** [comment]
This is looking good, thanks.

Actually, I think the offending mod is Thrayonlosa-ItemBlacklist. It modifies the method for firing the tricorn before my mod attempts the same, which results in an error in the log

```[Error  :TricornEliteEquipment] Failed to patch EquipmentSlot.FireBossHunter```

What then probably happens is when you fire it on an elite enemy that doesn't have a boss drop, it fails to find one and as my patch to default to the target's equipment hasn't gone through, it results to a null exception.

That's a guess for now until I get near my computer to test things, but you can do two things to test this hypothesis for now:
- Have all mods enabled and just fire the tricorn normally on a boss, which should work as expected.
- Disable the ItemBlacklist mod and check in the log output for the keyword TricornEliteEquipment, where the only messages should be applying hooks to some methods, but no error of failing to patch them. Obviously if that is the case, the game should also then behave properly.

**Comment by BrandonRosa** [comment]
Yep, you're 100% right. Both those things happened during testing!

**Comment by VaelophisNyx** [comment]
Should note I don't have the item blacklist mod mentioned here, but do have ZetAspects, and woudn't you know it, elites never drop equipment with this equipment (they do die though)

**Comment by SChinchi** [comment]
I'll need a log for that. There are other things that could be going wrong.

**Comment by VaelophisNyx** [comment]
I'll open an issue about it when I've got a log from a run where I try it
